---
title: "Class"
author: "Pieter Quinton"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rstanarm)
library(tidyverse)
```

```{r}

load("nes.rda")

data <- nes %>%
  select(year,
         partyid7,
         real_ideo,
         race_adj,
         age_discrete,
         educ1,
         female,
         income) %>%
  mutate_at(3:8, as.factor) %>%
  mutate(race = case_when(
    race_adj == 1 ~ "white",
    race_adj == 1.5 ~ "other",
    race_adj == 2 ~ "black"
  ))

```

```{r}

data %>%
  na.exclude(real_ideo) %>%
  group_by(year) %>%
  summarize(average = mean(real_ideo)) %>%
  ggplot(aes(x = year, y = average)) +
    geom_point() +
    geom_smooth(se = FALSE)

model <- data %>%
  drop_na()

summary(glm(partyid7 ~ real_ideo + race_adj + age_discrete + educ1 + female + income, data = model))

fit1 <- stan_glm(partyid7 ~ female, data = model, refresh = 0)

print(fit)
```

```{r}
one <- model %>%
  filter(female == 0,
         partyid7 >= (3.9-2.1),
         partyid7 <= (3.9 + 2.1)) %>%
  nrow()

two <- model %>%
  filter(female == 1,
         partyid7 >= (3.7 - 2.1),
         partyid7 <= (3.7 + 2.1)) %>%
  nrow()

(one + two)/length(model$partyid7)

```

```{r}
fit2 <- stan_glm(partyid7 ~ race, data = model, refresh = 0)

```

```{r}

model <- model %>%
  mutate(pred_gender = predict(fit1, model),
         pred_race = predict(fit2, model))
```

